### ISSUE TITLE
1.19.3 blur

### ISSUE THREAD

**Issue by blank3times** [voormann/dale-shader#6]
I know 1.19.3 has been messing with a few things, but since that update, dale seems to be very blurry for some reason, as if an effect was cranked way up automatically. Maybe anyone could tell me what changes were actually made, so even if we all have to do it each time we download it can be fixed? =]
![2023-01-04_08 04 09](https://user-images.githubusercontent.com/105398129/215019528-958aed11-9959-4b7e-b5bc-69162ef193ef.png)
(This image was perfect as a background that needed a blur effect, but other than that it's not ideal)

**Comment by blank3times** [comment]
When I say do it every time I mean like how at least for my computer you have to replace texture2D() with texture() on packs like DartCat's and Xilefian's.

**Comment by voormann** [comment]
I tried using texture() instead of texture2D(), but the game won't load the resource pack after applying the changes (at least on my computer on the latest 1.19.3 version of MC). Seems like this issue caused by the water blur effect being applied to the whole screen whenever there are particles somewhere in the frame. If you have a fork/download for your fix, I'd love to check it out :)

**Comment by blank3times** [comment]
I do not even have a fix :(. Texture2D is an example of what I do for cinematica because funnily enough, Texture2D actually is what makes cinematica not even load on my computer... it's identical besides version or something and ForSomeReason™ crashes my mc in the other direction...

I am not familiar with the post shaders very much, but someone hopefully can find something at some point, since I really love this pack! (Good job and thank you)

**Comment by blank3times** [comment]
Update: I think this is actually an incompatibility with new versions of Sodium. I'll reopen if I can get it to stop working on Vanilla (it works for me on 1.20.3 snapshots right now but those don't have Sodium and I think that's the reason it works now)
